# Generated by Django 4.2.3 on 2023-07-13 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=75)),
                ('brand', models.CharField(default='', max_length=30)),
                ('year', models.CharField(default='', max_length=15)),
                ('type', models.CharField(default='', max_length=20)),
                ('km', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('color', models.CharField(default='', max_length=20)),
                ('new', models.BooleanField(default=True)),
                ('vin', models.CharField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
